<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?php $this->headTitle(); ?>
        <meta charset="utf-8">
    </head>
    <body>
        <div class="container">
            <header>
                <p>
                    Sistema de Controle dos Lanternas Verdes
                </p>
            </header>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>
                    &copy; 2013 by Oa. <?php echo $this->translate('All rights reserved'); ?>    
                </p>
            </footer>            
        </div>
        <!-- /container -->
    </body>
</html>
